from src.model.actor import Actor
from src.model.movie import Movie
from src.model.genre import Genre
from src.model.nation import Nation
from src.model.director import Director
from src.model.movie_actor import MovieActor
from src.model.movie_genre import MovieGenre
from src.model.movie_nation import MovieNation
from src.model.movie_director import MovieDirector