"""Create Movie and Director Table

Revision ID: 7b649185c498
Revises: 
Create Date: 2021-12-12 23:45:24.527495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b649185c498'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('director_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('movie_cd', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_name', sa.String(length=64), nullable=False),
    sa.Column('movie_released_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('movie_image', sa.String(length=1024), nullable=False),
    sa.Column('movie_total_autidences', sa.Integer(), nullable=False),
    sa.Column('is_only_seoul', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('movie_cd')
    )
    op.create_table('movie_directors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('movie_cd', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['directors.id'], ),
    sa.ForeignKeyConstraint(['movie_cd'], ['movies.movie_cd'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_directors')
    op.drop_table('movies')
    op.drop_table('directors')
    # ### end Alembic commands ###
