"""Create Movie Table

Revision ID: 9babc0fc1709
Revises: 
Create Date: 2021-12-12 22:26:52.803136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9babc0fc1709'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('movie_cd', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_name', sa.String(length=64), nullable=False),
    sa.Column('movie_released_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('movie_image', sa.String(length=1024), nullable=False),
    sa.Column('movie_total_autidences', sa.Integer(), nullable=False),
    sa.Column('is_only_seoul', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('movie_cd')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
